const emoticonsImages = {
    roll: require('../../../img/emoticons/kostka.png'),
    smile: require('../../../img/emoticons/smile.png'),
    sad: require('../../../img/emoticons/sad.png'),
    wink: require('../../../img/emoticons/wink.png'),
    razz: require('../../../img/emoticons/razz.png'),
    grin: require('../../../img/emoticons/grin.png'),
    plain: require('../../../img/emoticons/plain.png'),
    surprise: require('../../../img/emoticons/surprise.png'),
    confused: require('../../../img/emoticons/confused.png'),
    glasses: require('../../../img/emoticons/glasses.png'),
    eek: require('../../../img/emoticons/eek.png'),
    cool: require('../../../img/emoticons/cool.png'),
    smilebig: require('../../../img/emoticons/smilebig.png'),
    crying: require('../../../img/emoticons/crying.png'),
    kiss: require('../../../img/emoticons/kiss.png'),
    angel: require('../../../img/emoticons/angel.png'),
    devilish: require('../../../img/emoticons/devilish.png'),
    monkey: require('../../../img/emoticons/monkey.png'),
    idea: require('../../../img/emoticons/idea.png'),
    important: require('../../../img/emoticons/important.png'),
    help: require('../../../img/emoticons/help.png'),
    error: require('../../../img/emoticons/error.png'),
    warning: require('../../../img/emoticons/warning.png'),
    favorite: require('../../../img/emoticons/favorite.png'),
    pepe: require('../../../img/emoticons/pepe.png'),
    internet_explorer: require('../../../img/emoticons/internet_explorer.png'),
    cebula: require('../../../img/emoticons/cebula.png'),
    nosacz: require('../../../img/emoticons/nosacz.jpg'),
    zolwik: require('../../../img/emoticons/zolwik.png'),
    gintoki: require('../../../img/emoticons/gintoki.png'),
    mis: require('../../../img/emoticons/mis.png'),
    gengar: require('../../../img/emoticons/gengar.png'),
    piplup: require('../../../img/emoticons/piplup.png'),
    naboki: require('../../../img/emoticons/naboki.png'),
    facepalm: require('../../../img/emoticons/facepalm.png'),
};

export default emoticonsImages;