services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Utils\:
    resource: '../../src/Utils'

  App\Utils\ChatConfig:
    arguments:
      $botId: '%env(BOT_ID)%'
      $rollCoolDown: '%env(ROLL_COLLDOWN)%'